version: "3.8"

services:
  api:
    # docker build -f apps/api/Dockerfile . --no-cache -t psyduck-nest
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        no-cache: "true"
    image: psyduck-nest
    ## for development
    # ports:
    #   - "8080:8080"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
