import {
  BarChart2Icon,
  BookUserIcon,
  Building2Icon,
  CircleUserIcon,
  FolderKanbanIcon,
  LogOutIcon,
  SettingsIcon,
  UsersIcon,
} from "lucide-react";
import { FolderIcon } from "@heroicons/react/24/outline";

const routes = {
  myworkspace: {
    name: "My Workspaces",
    href: "/my-workspaces",
    icon: FolderKanbanIcon,
    isPrimary: true,
    isSecondary: false,
    isAdmin: false,
    isMenu: false,
  },
  dashboard: {
    name: "Dashboard",
    href: "/admin/dashboard",
    icon: BarChart2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isMenu: false,
  },
  organization: {
    name: "Organizations",
    href: "/admin/organizations",
    icon: Building2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isMenu: false,
  },
  workspaces: {
    name: "Workspaces",
    href: "/admin/workspaces",
    icon: FolderIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isMenu: false,
  },
  clients: {
    name: "Clients",
    href: "/admin/clients",
    icon: BookUserIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isMenu: false,
  },
  users: {
    name: "Users",
    href: "/admin/users",
    icon: UsersIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isMenu: false,
  },
  settings: {
    name: "Settings",
    href: "/settings",
    icon: SettingsIcon,
    isPrimary: false,
    isSecondary: true,
    isAdmin: false,
    isMenu: false,
  },
  account: {
    name: "Account",
    href: "/account",
    icon: CircleUserIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isMenu: true,
  },
  signout: {
    name: "Sign out",
    href: "/signout",
    icon: LogOutIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isMenu: true,
  },
};

export default Object.entries(routes);
