import {
  BarChart2Icon,
  BookUserIcon,
  Building2Icon,
  CircleUserIcon,
  FolderKanbanIcon,
  LogOutIcon,
  SettingsIcon,
  UsersIcon,
  FolderIcon,
} from "lucide-react";

const routes = [
  {
    name: "Workspaces",
    href: "/workspaces",
    icon: FolderKanbanIcon,
    isPrimary: true,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Dashboard",
    href: "/admin/dashboard",
    icon: BarChart2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Organizations",
    href: "/admin/organizations",
    icon: Building2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Workspaces",
    href: "/admin/workspaces",
    icon: FolderIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Clients",
    href: "/admin/clients",
    icon: BookUserIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Users",
    href: "/admin/users",
    icon: UsersIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Settings",
    href: "/settings",
    icon: SettingsIcon,
    isPrimary: false,
    isSecondary: true,
    isAdmin: false,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Account",
    href: "/account",
    icon: CircleUserIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: false,
    isMenu: true,
  },
  {
    name: "Sign out",
    href: "/signout",
    icon: LogOutIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: false,
    isMenu: true,
  },
];

export default routes;
