import {
  BarChart2Icon,
  BookUserIcon,
  Building2Icon,
  CircleUserIcon,
  FolderKanbanIcon,
  LogOutIcon,
  SettingsIcon,
  UsersIcon,
  FolderIcon,
  Users2Icon,
  NotepadTextIcon,
} from "lucide-react";

const routes = [
  {
    name: "Workspaces",
    href: "/workspaces",
    icon: FolderKanbanIcon,
    isPrimary: true,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Settings",
    href: "/settings",
    icon: SettingsIcon,
    isPrimary: false,
    isSecondary: true,
    isAdmin: false,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Account",
    href: "/account",
    icon: CircleUserIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: false,
    isMenu: true,
  },
  {
    name: "Dashboard",
    href: "/admin/dashboard",
    icon: BarChart2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Organizations",
    href: "/admin/organizations",
    icon: Building2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Workspaces",
    href: "/admin/workspaces",
    icon: FolderIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Clients",
    href: "/admin/clients",
    icon: BookUserIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Users",
    href: "/admin/users",
    icon: UsersIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: true,
    isWorkspace: false,
    isMenu: false,
  },
  {
    name: "Sign out",
    href: "/signout",
    icon: LogOutIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: false,
    isMenu: true,
  },
  {
    name: "Notes",
    href: "/workspaces/:wid/notes",
    icon: NotepadTextIcon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: true,
    isMenu: false,
  },
  {
    name: "Clients",
    href: "/workspaces/:wid/clients",
    icon: Users2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: true,
    isMenu: false,
  },
  {
    name: "Members",
    href: "/workspaces/:wid/members",
    icon: Users2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: true,
    isMenu: false,
  },
  {
    name: "Settings",
    href: "/workspaces/:wid/settings",
    icon: Users2Icon,
    isPrimary: false,
    isSecondary: false,
    isAdmin: false,
    isWorkspace: true,
    isMenu: false,
  },
];

export const userNavigation = routes
  .filter((value) => value.isMenu)
  .map((value) => ({
    ...value,
    key: value.href.replace("/", ""),
  }));

export default routes;
