name: Dry Build

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    #  TURBO_REMOTE_ONLY: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Clear node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -rf package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  Notification:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ failure() }}
    steps:
      - name: Send failure email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ vars.EMAIL_USERNAME }}
          # app password https://support.google.com/mail/answer/185833?hl=en-GB
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: Failed to build ${{ github.repository }}
          body: "${{ github.actor}}!! Psyduck-nest build break: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          # comma-separated string
          to: ${{ vars.EMAIL_TO }}
          from: Psyduck
