name: Dry Build

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  Dry-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Run tests
        run: npm run test

  Notification:
    runs-on: ubuntu-latest
    needs: Dry-Build
    if: ${{ failure() }}
    steps:
      - name: Send failure email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ vars.EMAIL_USERNAME }}
          # app password https://support.google.com/mail/answer/185833?hl=en-GB
          password: ${{ secrets.EMAIL_APP_PASSWORD }}
          subject: Failed to build ${{ github.repository }}
          body: "${{ github.actor}}!! Psyduck-nest build break: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          # comma-separated string
          to: ${{ vars.EMAIL_TO }}
          from: Psyduck
